/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BenchmarkRouteImport } from './routes/benchmark'
import { Route as ConcesionariasRouteImport } from './routes/concesionarias'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexDothtmlRouteImport } from './routes/index[.]html'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaquinariasRouteImport } from './routes/maquinarias'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminEmpresasRouteImport } from './routes/admin/empresas'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as MaquinariasIndexRouteImport } from './routes/maquinarias/index'
import { Route as MaquinariasBenchmarkRouteImport } from './routes/maquinarias/benchmark'
import { Route as MaquinariasConcesionariasRouteImport } from './routes/maquinarias/concesionarias'
import { Route as MaquinariasIndicadoresRouteImport } from './routes/maquinarias/indicadores'
import { Route as PagesContactoDothtmlRouteImport } from './routes/pages/contacto[.]html'
import { Route as PagesNosotrosDothtmlRouteImport } from './routes/pages/nosotros[.]html'
import { Route as PagesServicio_nubeDothtmlRouteImport } from './routes/pages/servicio_nube[.]html'
import { Route as PagesServiciosDothtmlRouteImport } from './routes/pages/servicios[.]html'
import { Route as PortalDashboardRouteImport } from './routes/portal.dashboard'
import { Route as AdminServiciosNuevoRouteImport } from './routes/admin/servicios.nuevo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarkRoute = BenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcesionariasRoute = ConcesionariasRouteImport.update({
  id: '/concesionarias',
  path: '/concesionarias',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexDothtmlRoute = IndexDothtmlRouteImport.update({
  id: '/index.html',
  path: '/index.html',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaquinariasRoute = MaquinariasRouteImport.update({
  id: '/maquinarias',
  path: '/maquinarias',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const MaquinariasIndexRoute = MaquinariasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MaquinariasRoute,
} as any)
const MaquinariasBenchmarkRoute = MaquinariasBenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => MaquinariasRoute,
} as any)
const MaquinariasConcesionariasRoute =
  MaquinariasConcesionariasRouteImport.update({
    id: '/concesionarias',
    path: '/concesionarias',
    getParentRoute: () => MaquinariasRoute,
  } as any)
const MaquinariasIndicadoresRoute = MaquinariasIndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => MaquinariasRoute,
} as any)
const PagesContactoDothtmlRoute = PagesContactoDothtmlRouteImport.update({
  id: '/pages/contacto.html',
  path: '/pages/contacto.html',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesNosotrosDothtmlRoute = PagesNosotrosDothtmlRouteImport.update({
  id: '/pages/nosotros.html',
  path: '/pages/nosotros.html',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesServicio_nubeDothtmlRoute =
  PagesServicio_nubeDothtmlRouteImport.update({
    id: '/pages/servicio_nube.html',
    path: '/pages/servicio_nube.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagesServiciosDothtmlRoute = PagesServiciosDothtmlRouteImport.update({
  id: '/pages/servicios.html',
  path: '/pages/servicios.html',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/portal/dashboard',
  path: '/portal/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServiciosNuevoRoute = AdminServiciosNuevoRouteImport.update({
  id: '/servicios/nuevo',
  path: '/servicios/nuevo',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/benchmark': typeof BenchmarkRoute
  '/concesionarias': typeof ConcesionariasRoute
  '/contacto': typeof ContactoRoute
  '/index.html': typeof IndexDothtmlRoute
  '/indicadores': typeof IndicadoresRoute
  '/login': typeof LoginRoute
  '/maquinarias': typeof MaquinariasRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/servicios': typeof ServiciosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/maquinarias/benchmark': typeof MaquinariasBenchmarkRoute
  '/maquinarias/concesionarias': typeof MaquinariasConcesionariasRoute
  '/maquinarias/indicadores': typeof MaquinariasIndicadoresRoute
  '/pages/contacto.html': typeof PagesContactoDothtmlRoute
  '/pages/nosotros.html': typeof PagesNosotrosDothtmlRoute
  '/pages/servicio_nube.html': typeof PagesServicio_nubeDothtmlRoute
  '/pages/servicios.html': typeof PagesServiciosDothtmlRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/maquinarias/': typeof MaquinariasIndexRoute
  '/admin/servicios/nuevo': typeof AdminServiciosNuevoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benchmark': typeof BenchmarkRoute
  '/concesionarias': typeof ConcesionariasRoute
  '/contacto': typeof ContactoRoute
  '/index.html': typeof IndexDothtmlRoute
  '/indicadores': typeof IndicadoresRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/servicios': typeof ServiciosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/maquinarias/benchmark': typeof MaquinariasBenchmarkRoute
  '/maquinarias/concesionarias': typeof MaquinariasConcesionariasRoute
  '/maquinarias/indicadores': typeof MaquinariasIndicadoresRoute
  '/pages/contacto.html': typeof PagesContactoDothtmlRoute
  '/pages/nosotros.html': typeof PagesNosotrosDothtmlRoute
  '/pages/servicio_nube.html': typeof PagesServicio_nubeDothtmlRoute
  '/pages/servicios.html': typeof PagesServiciosDothtmlRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/maquinarias': typeof MaquinariasIndexRoute
  '/admin/servicios/nuevo': typeof AdminServiciosNuevoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/benchmark': typeof BenchmarkRoute
  '/concesionarias': typeof ConcesionariasRoute
  '/contacto': typeof ContactoRoute
  '/index.html': typeof IndexDothtmlRoute
  '/indicadores': typeof IndicadoresRoute
  '/login': typeof LoginRoute
  '/maquinarias': typeof MaquinariasRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/servicios': typeof ServiciosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/maquinarias/benchmark': typeof MaquinariasBenchmarkRoute
  '/maquinarias/concesionarias': typeof MaquinariasConcesionariasRoute
  '/maquinarias/indicadores': typeof MaquinariasIndicadoresRoute
  '/pages/contacto.html': typeof PagesContactoDothtmlRoute
  '/pages/nosotros.html': typeof PagesNosotrosDothtmlRoute
  '/pages/servicio_nube.html': typeof PagesServicio_nubeDothtmlRoute
  '/pages/servicios.html': typeof PagesServiciosDothtmlRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/maquinarias/': typeof MaquinariasIndexRoute
  '/admin/servicios/nuevo': typeof AdminServiciosNuevoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/benchmark'
    | '/concesionarias'
    | '/contacto'
    | '/index.html'
    | '/indicadores'
    | '/login'
    | '/maquinarias'
    | '/nosotros'
    | '/servicios'
    | '/admin/dashboard'
    | '/admin/empresas'
    | '/admin/usuarios'
    | '/maquinarias/benchmark'
    | '/maquinarias/concesionarias'
    | '/maquinarias/indicadores'
    | '/pages/contacto.html'
    | '/pages/nosotros.html'
    | '/pages/servicio_nube.html'
    | '/pages/servicios.html'
    | '/portal/dashboard'
    | '/admin/'
    | '/maquinarias/'
    | '/admin/servicios/nuevo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/benchmark'
    | '/concesionarias'
    | '/contacto'
    | '/index.html'
    | '/indicadores'
    | '/login'
    | '/nosotros'
    | '/servicios'
    | '/admin/dashboard'
    | '/admin/empresas'
    | '/admin/usuarios'
    | '/maquinarias/benchmark'
    | '/maquinarias/concesionarias'
    | '/maquinarias/indicadores'
    | '/pages/contacto.html'
    | '/pages/nosotros.html'
    | '/pages/servicio_nube.html'
    | '/pages/servicios.html'
    | '/portal/dashboard'
    | '/admin'
    | '/maquinarias'
    | '/admin/servicios/nuevo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/benchmark'
    | '/concesionarias'
    | '/contacto'
    | '/index.html'
    | '/indicadores'
    | '/login'
    | '/maquinarias'
    | '/nosotros'
    | '/servicios'
    | '/admin/dashboard'
    | '/admin/empresas'
    | '/admin/usuarios'
    | '/maquinarias/benchmark'
    | '/maquinarias/concesionarias'
    | '/maquinarias/indicadores'
    | '/pages/contacto.html'
    | '/pages/nosotros.html'
    | '/pages/servicio_nube.html'
    | '/pages/servicios.html'
    | '/portal/dashboard'
    | '/admin/'
    | '/maquinarias/'
    | '/admin/servicios/nuevo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BenchmarkRoute: typeof BenchmarkRoute
  ConcesionariasRoute: typeof ConcesionariasRoute
  ContactoRoute: typeof ContactoRoute
  IndexDothtmlRoute: typeof IndexDothtmlRoute
  IndicadoresRoute: typeof IndicadoresRoute
  LoginRoute: typeof LoginRoute
  MaquinariasRoute: typeof MaquinariasRouteWithChildren
  NosotrosRoute: typeof NosotrosRoute
  ServiciosRoute: typeof ServiciosRoute
  PagesContactoDothtmlRoute: typeof PagesContactoDothtmlRoute
  PagesNosotrosDothtmlRoute: typeof PagesNosotrosDothtmlRoute
  PagesServicio_nubeDothtmlRoute: typeof PagesServicio_nubeDothtmlRoute
  PagesServiciosDothtmlRoute: typeof PagesServiciosDothtmlRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmark': {
      id: '/benchmark'
      path: '/benchmark'
      fullPath: '/benchmark'
      preLoaderRoute: typeof BenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concesionarias': {
      id: '/concesionarias'
      path: '/concesionarias'
      fullPath: '/concesionarias'
      preLoaderRoute: typeof ConcesionariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index.html': {
      id: '/index.html'
      path: '/index.html'
      fullPath: '/index.html'
      preLoaderRoute: typeof IndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maquinarias': {
      id: '/maquinarias'
      path: '/maquinarias'
      fullPath: '/maquinarias'
      preLoaderRoute: typeof MaquinariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/maquinarias/': {
      id: '/maquinarias/'
      path: '/'
      fullPath: '/maquinarias/'
      preLoaderRoute: typeof MaquinariasIndexRouteImport
      parentRoute: typeof MaquinariasRoute
    }
    '/maquinarias/benchmark': {
      id: '/maquinarias/benchmark'
      path: '/benchmark'
      fullPath: '/maquinarias/benchmark'
      preLoaderRoute: typeof MaquinariasBenchmarkRouteImport
      parentRoute: typeof MaquinariasRoute
    }
    '/maquinarias/concesionarias': {
      id: '/maquinarias/concesionarias'
      path: '/concesionarias'
      fullPath: '/maquinarias/concesionarias'
      preLoaderRoute: typeof MaquinariasConcesionariasRouteImport
      parentRoute: typeof MaquinariasRoute
    }
    '/maquinarias/indicadores': {
      id: '/maquinarias/indicadores'
      path: '/indicadores'
      fullPath: '/maquinarias/indicadores'
      preLoaderRoute: typeof MaquinariasIndicadoresRouteImport
      parentRoute: typeof MaquinariasRoute
    }
    '/pages/contacto.html': {
      id: '/pages/contacto.html'
      path: '/pages/contacto.html'
      fullPath: '/pages/contacto.html'
      preLoaderRoute: typeof PagesContactoDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/nosotros.html': {
      id: '/pages/nosotros.html'
      path: '/pages/nosotros.html'
      fullPath: '/pages/nosotros.html'
      preLoaderRoute: typeof PagesNosotrosDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/servicio_nube.html': {
      id: '/pages/servicio_nube.html'
      path: '/pages/servicio_nube.html'
      fullPath: '/pages/servicio_nube.html'
      preLoaderRoute: typeof PagesServicio_nubeDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/servicios.html': {
      id: '/pages/servicios.html'
      path: '/pages/servicios.html'
      fullPath: '/pages/servicios.html'
      preLoaderRoute: typeof PagesServiciosDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/portal/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/servicios/nuevo': {
      id: '/admin/servicios/nuevo'
      path: '/servicios/nuevo'
      fullPath: '/admin/servicios/nuevo'
      preLoaderRoute: typeof AdminServiciosNuevoRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmpresasRoute: typeof AdminEmpresasRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminServiciosNuevoRoute: typeof AdminServiciosNuevoRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmpresasRoute: AdminEmpresasRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminServiciosNuevoRoute: AdminServiciosNuevoRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MaquinariasRouteChildren {
  MaquinariasBenchmarkRoute: typeof MaquinariasBenchmarkRoute
  MaquinariasConcesionariasRoute: typeof MaquinariasConcesionariasRoute
  MaquinariasIndicadoresRoute: typeof MaquinariasIndicadoresRoute
  MaquinariasIndexRoute: typeof MaquinariasIndexRoute
}

const MaquinariasRouteChildren: MaquinariasRouteChildren = {
  MaquinariasBenchmarkRoute: MaquinariasBenchmarkRoute,
  MaquinariasConcesionariasRoute: MaquinariasConcesionariasRoute,
  MaquinariasIndicadoresRoute: MaquinariasIndicadoresRoute,
  MaquinariasIndexRoute: MaquinariasIndexRoute,
}

const MaquinariasRouteWithChildren = MaquinariasRoute._addFileChildren(
  MaquinariasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BenchmarkRoute: BenchmarkRoute,
  ConcesionariasRoute: ConcesionariasRoute,
  ContactoRoute: ContactoRoute,
  IndexDothtmlRoute: IndexDothtmlRoute,
  IndicadoresRoute: IndicadoresRoute,
  LoginRoute: LoginRoute,
  MaquinariasRoute: MaquinariasRouteWithChildren,
  NosotrosRoute: NosotrosRoute,
  ServiciosRoute: ServiciosRoute,
  PagesContactoDothtmlRoute: PagesContactoDothtmlRoute,
  PagesNosotrosDothtmlRoute: PagesNosotrosDothtmlRoute,
  PagesServicio_nubeDothtmlRoute: PagesServicio_nubeDothtmlRoute,
  PagesServiciosDothtmlRoute: PagesServiciosDothtmlRoute,
  PortalDashboardRoute: PortalDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
